### ISSUE TITLE
Gimana Cara Menjalankannya?

### ISSUE THREAD

**Issue by mzaini30** [daberpro/javascript-style-sheet#1]
https://github.com/daberpro/javascript-style-sheet/blob/d454f9e85d1b7ef46496975874a3bd3abc4e7b4c/src/my-jss.js#L1-L36

Aku jalankan pakai `node main.js`, kok kayaknya nggak ngefek kode ini.

**Comment by daberpro** [comment]
Oalah, bang kode nya saya ubahblagi soalny kode compiler yang awal agak sedikit bug
